[server]
headless = true
maxUploadSize = 20
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"

[theme]
base = "light"
textColor = "#000000"
backgroundColor = "#f3f6fa"
secondaryBackgroundColor = "#87CEEB"
