[server]
headless = true
maxUploadSize = 20
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#1a5fb4"
textColor = "#111111"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
