[server]
headless = true
maxUploadSize = 20
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"

[theme]
base = "light"
textColor = "#111111"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e8f4fc"

[theme.dark]
textColor = "#f4f6f8"
backgroundColor = "#1b1d21"
secondaryBackgroundColor = "#2b2f36"
